### ISSUE TITLE
Typo on the package name?

### ISSUE THREAD

**Issue by antfu** [loonpwn/webpack-windicss-plugin#1]
`weback-windicss-plugin`
`webpack-windicss-plugin`

**Comment by loonpwn** [comment]
:man_facepalming: ...

Thank you. FYI this repo is very much in a prototype phase currently, will clean it up and migrate to the windicss org most likely tomorrow

**Comment by loonpwn** [comment]
Also @antfu this is pretty heavily reliant on your windicss util package with some potentially hacky webpack code. 

If you can spare any time to check over how the webpack code is setup, it would be very much appreciated. Was a lot of learning while putting it together so really not sure about best practices.
